sudo: required

services:
  - docker

script:
  - docker build -t jaydp17/jenkins-master:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jaydp17/jenkins-master:latest;
    fi  