version: '3.2'
services:
  jenkins:
    build: .
    privileged: true

    ports:
      - "${PORT}:8080"
      - "50000:50000"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./data
        target: /var/jenkins_home